### ISSUE TITLE
Problems in the console 

### ISSUE THREAD

**Issue by BenjaxxMC** [qIooIp/Notorious#16]
Please, fix this errores, they are apearing in the console, im using all the dependencies, in the correct versions.

Please fix it.

[17:52:20] [Craft Scheduler Thread - 1/WARN]: Exception in thread "Craft Scheduler Thread - 1" 
[17:52:20] [Craft Scheduler Thread - 1/WARN]: org.apache.commons.lang.UnhandledException: Plugin Notorious v2.1.0 generated an exception while executing task 28
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at me.qiooip.notorious.scoreboard.ScoreboardHandler$1.run(ScoreboardHandler.java:143)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

When im disabling it, another Chat issue appears in the console!!!

**Comment by qIooIp** [comment]
What permissions plugin are you using?

**Comment by BenjaxxMC** [comment]
Im using Permissionsex (the scoreboard only works 1 time when im instaled it)

That error apears me, and when that error doenst appears, this apears:

[17:10:22] [Craft Scheduler Thread - 64/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.IChatBaseComponent$ChatSerializer
[17:10:22] [Craft Scheduler Thread - 64/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[17:10:22] [Craft Scheduler Thread - 64/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[17:10:22] [Craft Scheduler Thread - 64/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[17:10:22] [Craft Scheduler Thread - 64/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[17:10:22] [Craft Scheduler Thread - 64/WARN]: 	at java.lang.Class.forName0(Native Method)
[17:10:22] [Craft Scheduler Thread - 64/WARN]: 	at java.lang.Class.forName(Unknown Source)
[17:10:22] [Craft Scheduler Thread - 64/WARN]: 	at me.drpiggy.pt.Main.getNMSClass(Main.java:156)
[17:10:22] [Craft Scheduler Thread - 64/WARN]: 	at me.drpiggy.pt.Main.sendActionBar(Main.java:188)
[17:10:22] [Craft Scheduler Thread - 64/WARN]: 	at me.drpiggy.pt.Main.access$0(Main.java:182)
[17:10:22] [Craft Scheduler Thread - 64/WARN]: 	at me.drpiggy.pt.Main$1.run(Main.java:46)
[17:10:22] [Craft Scheduler Thread - 64/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
[17:10:22] [Craft Scheduler Thread - 64/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[17:10:22] [Craft Scheduler Thread - 64/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:10:22] [Craft Scheduler Thread - 64/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:10:22] [Craft Scheduler Thread - 64/WARN]: 	at java.lang.Thread.run(Unknown Source)


You have the logs in the description
[logs errors.zip](https://github.com/qIooIp/Notorious/files/1275627/logs.errors.zip)

**Comment by Herblerp** [comment]
Hi

Use this server: [https://yivesmirror.com/grab/spigot/spigot-1.8.8-R0.1-SNAPSHOT.jar](url)
Use this permissions plugin (its the best one, trust me): [https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/](url)

That should fix the spamming and the scoreboard.

Good luck,
Herb

**Comment by BenjaxxMC** [comment]
Luck perms doesnt work in 1.8.8 jar version, this is the reason that i change to 1.8

**Comment by qIooIp** [comment]
There is a problem regarding Vault compatibility with new Permissions plugins. I will persist on changing whole Notorious rank detecting system with simple permissions simple in next update.

**Comment by BenjaxxMC** [comment]
Same error, please recode the plugin, or fix this bug, there are some many tasks that are failing....

Some tasks like, to the task 20 to the task 40
[errorlog.zip](https://github.com/qIooIp/Notorious/files/1278949/errorlog.zip)

thanks a lot for helping me :""v, im working for a network, and many players want to play this awesome game!

**Comment by Herblerp** [comment]
Try making a clean install using HCfactions, Luckperms, Notorious, and the required plugins (WE, WG, Vault). That should work (it works for me). Than add every plugin one at a time and check which one is causing trouble. Do not use Mango! Its a complete mess and it WILL fuck up your server.

**Comment by BenjaxxMC** [comment]
in 1st place, HCfaction plugin is only aviable on 1.9 version, and Notorious 1.7 - 1.8

Im using all the dependencies in the exact version in 1.8.8 minecraft client......


please Help With the Versions!!!

**Comment by BenjaxxMC** [comment]
And with these https://www.spigotmc.org/resources/hcfactions.46717/history similar plugin, notorious doesnt enable well

**Comment by qIooIp** [comment]
This is not original HCFactions. Please use http://www.mc-market.org/resources/1336/history.

**Comment by qIooIp** [comment]
1. Error occurred because you are using Spigot 1.8, but your plugin requires 1.8.1-R1.
2. Error is due to PermissionsX implementation with Vault - I don't know what this is a problem since Vault supports PermissionsX. To fix this error update to latest Notorious version and make sure to read Update log to change settings that are needed for latest version to work properly.

**Comment by BenjaxxMC** [comment]
what is 1.8.1-R1?

**Comment by BenjaxxMC** [comment]
Where can i find 1.8.1 spigot .jar server¿

**Comment by qIooIp** [comment]
This line: "java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.IChatBaseComponent$ChatSerializer" means that your version doesn't have this class in it. I would suggest you to use PaperSpigot since it have new classes and methods supported. You can download 1.8 PaperSpigot from https://yivesmirror.com/grab/paperspigot/PaperSpigot-1.8-R0.1-SNAPSHOT-b235.jar

**Comment by BenjaxxMC** [comment]
Thanks For all, best support can i see, well the plugin is working perfectly with any problem


Thanks For the help!!

**Comment by qIooIp** [comment]
Glad to hear that.
