### ISSUE TITLE
Crowbar error

### ISSUE THREAD

**Issue by jeffmdun** [qIooIp/Notorious#17]
[19:49:30] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Notorious v2.1.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-PaperSpigot-ea452ce]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-ea452ce]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [server.jar:git-PaperSpigot-ea452ce]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [server.jar:git-PaperSpigot-ea452ce]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:242) [server.jar:git-PaperSpigot-ea452ce]
	at net.minecraft.server.v1_7_R4.PlayerInteractManager.dig(PlayerInteractManager.java:103) [server.jar:git-PaperSpigot-ea452ce]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:555) [server.jar:git-PaperSpigot-ea452ce]
	at net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:41) [server.jar:git-PaperSpigot-ea452ce]
	at net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.handle(PacketPlayInBlockDig.java:65) [server.jar:git-PaperSpigot-ea452ce]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [server.jar:git-PaperSpigot-ea452ce]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [server.jar:git-PaperSpigot-ea452ce]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:794) [server.jar:git-PaperSpigot-ea452ce]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [server.jar:git-PaperSpigot-ea452ce]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:642) [server.jar:git-PaperSpigot-ea452ce]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:548) [server.jar:git-PaperSpigot-ea452ce]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [server.jar:git-PaperSpigot-ea452ce]
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_141]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_141]
	at me.qiooip.notorious.handlers.CrowbarHandler.getUses(CrowbarHandler.java:190) ~[?:?]
	at me.qiooip.notorious.handlers.CrowbarHandler.onPlayerInteract(CrowbarHandler.java:80) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_141]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[server.jar:git-PaperSpigot-ea452ce]
	... 15 more

**Comment by qIooIp** [comment]
Have you changed anything regarding crowbar in config.yml?

**Comment by jeffmdun** [comment]
I changed it so that it doesn't allow the break of end portal frames, and then reversed it back to the original and i was still getting errors

**Comment by qIooIp** [comment]
Paste your config.yml to https://hastebin.com.

**Comment by jeffmdun** [comment]
https://hastebin.com/etoburakul.coffeescript

**Comment by qIooIp** [comment]
Please return "crowbar-lore" to as it was before:
crowbar-lore:
- '&5Spawners: &a{&c<scount>&a}'
- '&5Portals: &a{&c<pcount>&a}'

You can change colors but not remove whole lines.
