### ISSUE TITLE
ERROR while players login 

### ISSUE THREAD

**Issue by Kerbyy** [qIooIp/Notorious#3]
[23:52:53 WARN]: Exception in thread "Craft Scheduler Thread - 21"
[23:52:53 WARN]: org.apache.commons.lang.UnhandledException: Plugin Notorious v2.0.5 generated an exception while executing task 16
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at me.qiooip.notorious.scoreboard.ScoreboardHandler$1.run(ScoreboardHandler.java:141)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
        ... 3 more
pls help idk whats wrong

**Comment by ItsNature** [comment]
How often does this error occur?

**Comment by qIooIp** [comment]
Can you please delete your playerdata folder and try restarting your server?

**Comment by qIooIp** [comment]
This has been fixed in latest Notorious update. Follow instructions in Update Log to setup it properly since some things were changed in config.yml.
