### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by M4T14SG4M3R** [qIooIp/Notorious#9]
``
 ERROR]: Could not pass event BlockBreakEvent to Notorious v2.0.9
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[HCF.jar:git-PaperSpigot-ea452ce]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[HCF.jar:git-PaperSpigot-ea452ce]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [HCF.jar:git-PaperSpigot-ea452ce]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.PlayerInteractManager.breakBlock(PlayerInteractManager.java:264) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.PlayerInteractManager.dig(PlayerInteractManager.java:118) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:555) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:41) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.handle(PacketPlayInBlockDig.java:65) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:794) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:642) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:548) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [HCF.jar:git-PaperSpigot-ea452ce]
Caused by: java.lang.NullPointerException
        at me.qiooip.notorious.games.mountain.MountainHandler.onBlockBreak2(MountainHandler.java:252) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor210.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) `~[HCF.jar:git-PaperSpigot-ea452ce]`
        ... 15 more` This just appeared in my console and i didn't made the glowstone mountain ye

`issued server command: /mountain respawn OreMountain
[12:57:10 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mountain' in plugin Notorious v2.0.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[HCF.jar:git-PaperSpigot-ea452ce]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[HCF.jar:git-PaperSpigot-ea452ce]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:765) ~[HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1047) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:884) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:794) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:642) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:548) [HCF.jar:git-PaperSpigot-ea452ce]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [HCF.jar:git-PaperSpigot-ea452ce]
Caused by: java.lang.NullPointerException
        at me.qiooip.notorious.games.mountain.Mountain.paste(Mountain.java:34) ~[?:?]
        at me.qiooip.notorious.games.commands.mountain.MountainRespawn.execute(MountainRespawn.java:32) ~[?:?]
        at me.qiooip.notorious.games.commands.mountain.MountainCommandHandler.onCommand(MountainCommandHandler.java:98) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[HCF.jar:git-PaperSpigot-ea452ce]
        ... 13 more
` This when i made the Ore mountain and typed /mountain respawn OreMountain

**Comment by oMontey** [comment]
As long as the plugins working, this doesnt matter, if ur having trouble with glowstone mountain, use this plugin.. https://www.spigotmc.org/resources/glowstone-mountain-2-0-hcf-1-8-x-1-7-x.26772/history !
also! heres a screenshot of which version to use! https://gyazo.com/09fc960d36979134a531433d2cedc949

**Comment by M4T14SG4M3R** [comment]
I already had a glowstone mountain plugin in the last maps, but i wanted to use the notorious one to reduce the plugin size but it sent those errors

**Comment by oMontey** [comment]
just use the plugin i sent. its not even that big of a plugin

**Comment by qIooIp** [comment]
Fixed. Updating later today.
